baseURL = 'https://guzhongyi.pages.dev/'
locale = 'zh-cn'
title = '古中医'
timeZone = "Asia/Shanghai"


# 主题
theme = "PaperMod"

# 直接生成一级目录
uglyURLs = true

[menu] # Menu management
	[[menu.main]]
		name = '首页'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = '关于我们'
		pageRef = '/posts/about.html'
		weight = 15

[params]
	DateFormat = "2006-01-02 15:04:05"
	showTOC = true
	